<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <AssemblyName>PowSaveEditor</AssemblyName>
    <RootNamespace>PowSaveEditor</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
